#!/usr/bin/env python3

import passwordshaker, sys

if len(sys.argv) != 2 or sys.argv[1] not in ('get','store'):
  sys.exit('usage: git-credential-pws get/store')

info = dict(line.rstrip().partition('=')[::2] for line in sys.stdin)
try:
  host = info['host']
  options = passwordshaker.load_options(host)
except Exception as e:
  sys.exit('error: {}'.format(e))

if 'username' in info:
  options['username'] = info['username']

if sys.argv[1] == 'get':
  print(passwordshaker.header, file=sys.stderr)
  password = passwordshaker.password(**options)
  print('password={}'.format(password))
  if 'username' in options:
    print('username={}'.format(options['username']))

elif sys.argv[1] == 'store':
  passwordshaker.save_options(host, options)
