#!/usr/bin/env python3

import passwordshaker, sys

print(passwordshaker.header, file=sys.stderr)

if len(sys.argv) != 2 or sys.argv[1] != 'get':
  sys.exit('usage: git-credential-pws get')

info = dict(line.rstrip().partition('=')[::2] for line in sys.stdin)
if 'host' not in info:
  sys.exit('invalid input')

options = passwordshaker.load_options(info['host'])
password = passwordshaker.password(**options)

print('password={}'.format(password))
